
export const types = {
    login: '[Auth] Login',
    logout: '[Auth] Logout',
    uiSetError: '[UI] Set Error',
    uiRemoveError: '[UI] Remove Error',
    uiStartLoading: '[UI] Start Loading',
    uiFinishLoading: '[UI] Finish Loading',
    productAddNew: '[Product] Add New Product',
    productLoad: '[Product] Load Products',
    productUpdate: '[Product] Update Products',
    productFileUrl: '[Product] Upload File Url',
    productDeleted: '[Product] Delete Products',
    productLogoutCleaning: '[Product] Logout Cleaning Product',
    cartAddProduct: '[CART] Add New Product',
    cartAddExistingProduct: '[CART] Add Existing Product',
    cartRemoveProduct: '[CART] Remove Cart Product',
    cartUpdatePriceTotal: '[CART] Update Price Total',
    cartUpdateAmount: '[CART] Update Amount',
}